### ISSUE TITLE
'gpt-4-1106-preview' does not exist.

### ISSUE THREAD

**Issue by monsterlady** [samuelcardillo/StarCitizen-AI#1]
BadRequestError: 400 The requested model 'gpt-4-1106-preview' does not exist.

**Comment by monsterlady** [comment]
> BadRequestError: 400 The requested model 'gpt-4-1106-preview' does not exist.

solved by topping-up 10 dollars credits in openai account

**Comment by samuelcardillo** [comment]
Yep that's from your account
